import os
from pathlib import Path
from datetime import datetime
from typing import Literal

# ── PDF ──────────────────────────────────────────────────────────────────────
def _export_pdf(title: str, content: str, output_path: str) -> str:
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.lib import colors
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, HRFlowable
    )

    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter,
        leftMargin=1 * inch,
        rightMargin=1 * inch,
        topMargin=1 * inch,
        bottomMargin=1 * inch,
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "IvyTitle",
        parent=styles["Title"],
        fontSize=20,
        textColor=colors.HexColor("#1a1a2e"),
        spaceAfter=6,
        fontName="Helvetica-Bold",
    )
    meta_style = ParagraphStyle(
        "IvyMeta",
        parent=styles["Normal"],
        fontSize=9,
        textColor=colors.HexColor("#888888"),
        spaceAfter=14,
        fontName="Helvetica",
    )
    body_style = ParagraphStyle(
        "IvyBody",
        parent=styles["Normal"],
        fontSize=11,
        leading=17,
        textColor=colors.HexColor("#222222"),
        fontName="Helvetica",
        spaceAfter=8,
    )
    heading_style = ParagraphStyle(
        "IvyHeading",
        parent=styles["Heading2"],
        fontSize=13,
        textColor=colors.HexColor("#1a1a2e"),
        fontName="Helvetica-Bold",
        spaceBefore=14,
        spaceAfter=4,
    )

    story = []

    # Title block
    story.append(Paragraph(title, title_style))
    generated = datetime.now().strftime("%B %d, %Y at %H:%M")
    story.append(Paragraph(f"Generated by Ivy Assistant · {generated}", meta_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#cccccc")))
    story.append(Spacer(1, 14))

    # Parse content — lines starting with ## become headings
    for line in content.split("\n"):
        stripped = line.strip()
        if not stripped:
            story.append(Spacer(1, 6))
        elif stripped.startswith("## "):
            story.append(Paragraph(stripped[3:], heading_style))
        elif stripped.startswith("# "):
            story.append(Paragraph(stripped[2:], heading_style))
        else:
            # Escape XML special chars for ReportLab
            safe = (
                stripped
                .replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
            )
            story.append(Paragraph(safe, body_style))

    doc.build(story)
    return output_path


# ── DOCX ─────────────────────────────────────────────────────────────────────
def _export_docx(title: str, content: str, output_path: str) -> str:
    from docx import Document
    from docx.shared import Pt, RGBColor, Inches
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    doc = Document()

    # Page margins
    for section in doc.sections:
        section.top_margin = Inches(1)
        section.bottom_margin = Inches(1)
        section.left_margin = Inches(1)
        section.right_margin = Inches(1)

    # Title
    title_para = doc.add_paragraph()
    title_para.alignment = WD_ALIGN_PARAGRAPH.LEFT
    run = title_para.add_run(title)
    run.bold = True
    run.font.size = Pt(20)
    run.font.color.rgb = RGBColor(0x1A, 0x1A, 0x2E)

    # Meta line
    meta = doc.add_paragraph()
    generated = datetime.now().strftime("%B %d, %Y at %H:%M")
    meta_run = meta.add_run(f"Generated by Ivy Assistant · {generated}")
    meta_run.font.size = Pt(9)
    meta_run.font.color.rgb = RGBColor(0x88, 0x88, 0x88)

    doc.add_paragraph()  # spacer

    # Content
    for line in content.split("\n"):
        stripped = line.strip()
        if not stripped:
            doc.add_paragraph()
        elif stripped.startswith("## ") or stripped.startswith("# "):
            text = stripped.lstrip("# ").strip()
            h = doc.add_paragraph()
            hr = h.add_run(text)
            hr.bold = True
            hr.font.size = Pt(13)
            hr.font.color.rgb = RGBColor(0x1A, 0x1A, 0x2E)
        else:
            p = doc.add_paragraph()
            p.add_run(stripped).font.size = Pt(11)

    doc.save(output_path)
    return output_path


# ── TXT ──────────────────────────────────────────────────────────────────────
def _export_txt(title: str, content: str, output_path: str) -> str:
    generated = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    sep = "=" * 60
    report = f"{sep}\n{title}\nGenerated: {generated}\n{sep}\n\n{content}\n\n{sep}"
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(report)
    return output_path


# ── Public function ───────────────────────────────────────────────────────────
def summarize_and_export(
    content: str,
    title: str = "Summary Report",
    format: Literal["pdf", "docx", "txt"] = "pdf",
    save_dir: str = "data/reports",
) -> dict:
    """
    Summarize content and export it as a downloadable file.

    Args:
        content: The text content to include in the document
        title:   Document title shown in header
        format:  Output format — 'pdf', 'docx', or 'txt'
        save_dir: Directory to save the file

    Returns:
        dict with 'file_path', 'format', 'title', and 'message'
    """
    Path(save_dir).mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_title = title.replace(" ", "_").replace("/", "-")[:40]
    filename = f"{safe_title}_{timestamp}.{format}"
    output_path = str(Path(save_dir) / filename)

    try:
        if format == "pdf":
            _export_pdf(title, content, output_path)
        elif format == "docx":
            _export_docx(title, content, output_path)
        elif format == "txt":
            _export_txt(title, content, output_path)
        else:
            return {"error": f"Unsupported format: {format}"}

        size_kb = round(os.path.getsize(output_path) / 1024, 1)
        return {
            "file_path": output_path,
            "filename": filename,
            "format": format,
            "title": title,
            "size_kb": size_kb,
            "message": f"File saved: {output_path} ({size_kb} KB)",
        }
    except Exception as e:
        return {"error": f"Export failed ({format}): {e}"}


# Claude tool schema
SUMMARIZE_EXPORT_TOOL_SCHEMA = {
    "name": "summarize_and_export",
    "description": (
        "Summarize content and export it as a downloadable file. "
        "Supports PDF, DOCX, and TXT formats. "
        "Use when the user wants a document, report, or summary they can download."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "content": {
                "type": "string",
                "description": "The full text content to write into the document. Use ## for section headings.",
            },
            "title": {
                "type": "string",
                "description": "The document title shown in the header",
                "default": "Summary Report",
            },
            "format": {
                "type": "string",
                "enum": ["pdf", "docx", "txt"],
                "description": "Output file format: 'pdf', 'docx', or 'txt'",
                "default": "pdf",
            },
            "save_dir": {
                "type": "string",
                "description": "Directory to save the file (default: data/reports)",
                "default": "data/reports",
            },
        },
        "required": ["content"],
    },
}